"""Add table Users

Revision ID: ff2ce4340d9f
Revises: 625e4374c306
Create Date: 2024-08-06 13:20:50.206615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff2ce4340d9f'
down_revision: Union[str, None] = '625e4374c306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('priority', sa.String(), nullable=True))
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'date_to',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subtasks', 'priority')
    # ### end Alembic commands ###
